In [2]:
import numpy as np

import pandas as pd

In [8]:
arr = {'a':10, 'b':5, 'c':21}

q1 = pd.Series(arr)

print(q1)


a    10
b     5
c    21
dtype: int64


In [12]:
q2 = np.array((-8, -3, 2, 11))
print(q2)

[-8 -3  2 11]


In [17]:
q3 = np.array(( -5, 3, 2, 6, 9, -11))
q3 = q3.reshape(2,3)
print(q3)

[[ -5   3   2]
 [  6   9 -11]]
